//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEntityFramework.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ContextoHospital : DbContext
    {
        public ContextoHospital()
            : base("name=ContextoHospital")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEPT> DEPT { get; set; }
        public virtual DbSet<EMP> EMP { get; set; }
    
        public virtual int SubirSalarioOficio(string oficio, Nullable<int> incr)
        {
            var oficioParameter = oficio != null ?
                new ObjectParameter("oficio", oficio) :
                new ObjectParameter("oficio", typeof(string));
    
            var incrParameter = incr.HasValue ?
                new ObjectParameter("incr", incr) :
                new ObjectParameter("incr", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SubirSalarioOficio", oficioParameter, incrParameter);
        }
    
        public virtual ObjectResult<EMP> TODOSEMP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EMP>("TODOSEMP");
        }
    
        public virtual ObjectResult<EMP> TODOSEMP(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EMP>("TODOSEMP", mergeOption);
        }
    }
}
