//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEntityFramework.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ContextoHospital : DbContext
    {
        public ContextoHospital()
            : base("name=ContextoHospital")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEPT> DEPT { get; set; }
        public virtual DbSet<EMP> EMP { get; set; }
        public virtual DbSet<DOCTOR> DOCTOR { get; set; }
        public virtual DbSet<HOSPITAL> HOSPITAL { get; set; }
        public virtual DbSet<VISTADOCPLANT> VISTADOCPLANT { get; set; }
    
        public virtual int SubirSalarioOficio(string oficio, Nullable<int> incr)
        {
            var oficioParameter = oficio != null ?
                new ObjectParameter("oficio", oficio) :
                new ObjectParameter("oficio", typeof(string));
    
            var incrParameter = incr.HasValue ?
                new ObjectParameter("incr", incr) :
                new ObjectParameter("incr", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SubirSalarioOficio", oficioParameter, incrParameter);
        }
    
        public virtual ObjectResult<EMP> TODOSEMP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EMP>("TODOSEMP");
        }
    
        public virtual ObjectResult<EMP> TODOSEMP(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EMP>("TODOSEMP", mergeOption);
        }
    
        public virtual ObjectResult<PAGINAR_DEPT_Result> PAGINAR_DEPT(Nullable<int> pOSICION)
        {
            var pOSICIONParameter = pOSICION.HasValue ?
                new ObjectParameter("POSICION", pOSICION) :
                new ObjectParameter("POSICION", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PAGINAR_DEPT_Result>("PAGINAR_DEPT", pOSICIONParameter);
        }
    
        public virtual ObjectResult<PAGINARGRUPO_Result> PAGINARGRUPO(Nullable<int> pOSICION, ObjectParameter rEGISTROS)
        {
            var pOSICIONParameter = pOSICION.HasValue ?
                new ObjectParameter("POSICION", pOSICION) :
                new ObjectParameter("POSICION", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PAGINARGRUPO_Result>("PAGINARGRUPO", pOSICIONParameter, rEGISTROS);
        }
    
        public virtual ObjectResult<PAGINARHOSPITALES_Result> PAGINARHOSPITALES(Nullable<int> pOSICION, ObjectParameter rEGISTROS)
        {
            var pOSICIONParameter = pOSICION.HasValue ?
                new ObjectParameter("POSICION", pOSICION) :
                new ObjectParameter("POSICION", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PAGINARHOSPITALES_Result>("PAGINARHOSPITALES", pOSICIONParameter, rEGISTROS);
        }
    
        public virtual ObjectResult<VISTADOCPLANT> PROCEDVISTA(Nullable<int> pOSICION, ObjectParameter rEGISTROS, Nullable<int> pARAM)
        {
            var pOSICIONParameter = pOSICION.HasValue ?
                new ObjectParameter("POSICION", pOSICION) :
                new ObjectParameter("POSICION", typeof(int));
    
            var pARAMParameter = pARAM.HasValue ?
                new ObjectParameter("PARAM", pARAM) :
                new ObjectParameter("PARAM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VISTADOCPLANT>("PROCEDVISTA", pOSICIONParameter, rEGISTROS, pARAMParameter);
        }
    
        public virtual ObjectResult<VISTADOCPLANT> PROCEDVISTA(Nullable<int> pOSICION, ObjectParameter rEGISTROS, Nullable<int> pARAM, MergeOption mergeOption)
        {
            var pOSICIONParameter = pOSICION.HasValue ?
                new ObjectParameter("POSICION", pOSICION) :
                new ObjectParameter("POSICION", typeof(int));
    
            var pARAMParameter = pARAM.HasValue ?
                new ObjectParameter("PARAM", pARAM) :
                new ObjectParameter("PARAM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VISTADOCPLANT>("PROCEDVISTA", mergeOption, pOSICIONParameter, rEGISTROS, pARAMParameter);
        }
    }
}
