//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPT
    {
        public int DEPT_NO { get; set; }
        public string DNOMBRE { get; set; }
        public string LOC { get; set; }
    }
}
