//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP
    {
        public int EMP_NO { get; set; }
        public string APELLIDO { get; set; }
        public string OFICIO { get; set; }
        public Nullable<int> DIR { get; set; }
        public Nullable<System.DateTime> FECHA_ALT { get; set; }
        public Nullable<int> SALARIO { get; set; }
        public Nullable<int> COMISION { get; set; }
        public Nullable<int> DEPT_NO { get; set; }
    }
}
