<?xml version="1.0" encoding="utf-8"?><Database Name="Hospital" Class="ContextoHospitalDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LOCALHOST;Initial Catalog=Hospital;Persist Security Info=True;User ID=SA" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HospitalConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ENFERMO" Member="ENFERMOs">
    <Type Name="ENFERMO">
      <Column Name="INSCRIPCION" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="APELLIDO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIRECCION" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FECHA_NAC" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="S" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NSS" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DOCTOR" Member="DOCTORs">
    <Type Name="DOCTOR">
      <Column Name="HOSPITAL_COD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOCTOR_NO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="APELLIDO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ESPECIALIDAD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SALARIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DEPT" Member="DEPTs">
    <Type Name="DEPT">
      <Column Name="DEPT_NO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DNOMBRE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LOC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EMP" Member="EMPs">
    <Type Name="EMP">
      <Column Name="EMP_NO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="APELLIDO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OFICIO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FECHA_ALT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SALARIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="COMISION" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DEPT_NO" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PLANTILLA" Member="PLANTILLAs">
    <Type Name="PLANTILLA">
      <Column Name="HOSPITAL_COD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SALA_COD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EMPLEADO_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="APELLIDO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FUNCION" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="T" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SALARIO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOSPITAL" Member="HOSPITALs">
    <Type Name="HOSPITAL">
      <Column Name="HOSPITAL_COD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIRECCION" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TELEFONO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NUM_CAMA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.EliminarDept" Method="EliminarDept">
    <Parameter Name="dept_no" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ModificarSalario" Method="ModificarSalario">
    <Parameter Name="INCR" Parameter="iNCR" Type="System.Int32" DbType="Int" />
    <Parameter Name="DEPT_NO" Parameter="dEPT_NO" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.EliminarPlantilla" Method="EliminarPlantilla">
    <Parameter Name="emp_no" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>