//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaLINQSaraBachiller.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTAPEDIDOS
    {
        public long Posicion { get; set; }
        public string CodigoCliente { get; set; }
        public string NombreProducto { get; set; }
        public string Precio { get; set; }
        public Nullable<int> PrecioTotal { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<System.DateTime> FechaPedido { get; set; }
    }
}
